name: Update Prices Cache

on:
  schedule:
    # Mon–Fri at 22:15 UTC (safe after US close regardless of DST)
    - cron: "15 22 * * 1-5"
  workflow_dispatch: {}
  push:
    paths:
      - "mm_top_20.csv"
      - "ticker_map.csv"
      - "scripts/build_prices_cache.py"
      - ".github/workflows/update_prices.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "yfinance[fast]==0.2.43" curl_cffi pandas pyarrow numpy

      - name: Build parquet
        run: python scripts/build_prices_cache.py

      - name: Commit & push if changed
        run: |
          set -e
          if git status --porcelain prices_cache.parquet | grep -q .; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add prices_cache.parquet
            git commit -m "Update prices cache"
            git push
          else
            echo "No parquet changes; skipping commit."
          fi
